import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, MotionConfig, useReducedMotion } from 'motion/react';
import '@fontsource/barlow-condensed/latin-500.css';
import '@fontsource/barlow-condensed/latin-600.css';
import '@fontsource/ibm-plex-sans/latin-400.css';
import '@fontsource/ibm-plex-sans/latin-500.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import ParticleText from './components/ParticleText';
import ProcessPath from './components/ProcessPath';
import kinetiqVideo from '../kinetiq-demo.mp4';
import kinetiqPoster from '../kinetiq-poster.jpg';
import biteVideo from '../biteright-demo.mp4';
import bitePoster from '../biteright-poster.jpg';
import profile from '../profile.jpg';
import './style.css';

const chapters=[['intro','Index'],['kinetiq','KinetiQ'],['bite-right','Bite Right'],['archive','More work'],['about','About']];
const phases=[['Ready position','Establish the starting pose before the motion begins.'],['Load','Identify the preparation phase and the joint positions leading into the movement.'],['Set point','Isolate the transition between preparation and release.'],['Release','Inspect the release phase against the expected joint-angle ranges.'],['Follow-through','Review how the movement finishes after release.']];
function Disclosure({title,children}:{title:string;children:React.ReactNode}){
 const [open,setOpen]=useState(false);
 const id=title.toLowerCase().replace(/[^a-z]+/g,'-');
 return <div className="disclosure"><button aria-expanded={open} aria-controls={id} onClick={()=>setOpen(!open)}>{title}<span aria-hidden="true">{open?'−':'+'}</span></button><AnimatePresence initial={false}>{open&&<motion.div id={id} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.24}}><div className="disclosure-content">{children}</div></motion.div>}</AnimatePresence></div>;
}
function Demo({name,src,poster}:{name:string;src:string;poster:string}){
 return <figure className="demo"><div className="demo-bar"><span>Recorded product walkthrough</span><span>{name}</span></div><video controls playsInline preload="none" poster={poster} aria-label={`${name} product demonstration`}><source src={src} type="video/mp4"/><a href={src}>Download demo</a></video><figcaption>Actual application footage. Use the player controls to explore.</figcaption></figure>;
}
function App(){
 const preference=useReducedMotion();const [paused,setPaused]=useState(false);const [active,setActive]=useState('intro');const [phase,setPhase]=useState(0);
 const calm=Boolean(preference||paused);
 useEffect(()=>{const update=()=>{let id='intro';chapters.forEach(([key])=>{if((document.getElementById(key)?.getBoundingClientRect().top??Infinity)<innerHeight*.45)id=key;});setActive(id);};addEventListener('scroll',update,{passive:true});update();return()=>removeEventListener('scroll',update);},[]);
 return <MotionConfig reducedMotion={calm?'always':'user'}><a className="skip-link" href="#kinetiq">Skip to selected work</a>
 <header><a className="wordmark" href="#intro">PM<span> / </span>PARTH MOHAN</a><nav aria-label="Main navigation"><a href="#kinetiq">Work</a><a href="#about">About</a><a href="mailto:parthmohan2006@gmail.com">Contact</a></nav><button className="motion-toggle" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{calm?'Motion off':'Motion on'}</button></header>
 <aside className="chapter-nav" aria-label="Project chapters">{chapters.map(([id,label],i)=><a key={id} href={`#${id}`} aria-label={label} aria-current={active===id?'location':undefined}><span>0{i}</span><span>{label}</span></a>)}</aside>
 <main>
 <section id="intro" className="hero"><div className="hero-top"><span className="eyebrow">Personal portfolio / Selected works</span><span className="eyebrow">CS + Machine Learning / UMD</span></div><h1><span className="sr-only">Parth Mohan</span>{calm?<span className="static-name" aria-hidden="true">PARTH MOHAN</span>:<div aria-hidden="true"><ParticleText text="PARTH MOHAN" fontFamily="Barlow Condensed" fontWeight={600} fontSize="clamp(80px, 17vw, 270px)" color="#292c26" highlightColor="#292c26" pointerRepel={0} idleDrift={0} glow={false} scatter={65} density={3} particleSize={1.7} gatherDuration={1400} stagger={150}/></div>}</h1><div className="hero-copy"><p className="eyebrow accent">Software. Systems. Things that work.</p><h2>I build things.<br/>Then figure out<br/><em>what breaks.</em></h2><p>Computer vision, useful AI, and the engineering that connects an idea to a working product.</p><a className="text-link" href="#kinetiq">Explore selected work <span>01 / 05</span></a></div><div className="hero-bottom"><span>Built by Parth. Explained from the inside.</span><span>Scroll through the work</span></div></section>
 <section id="kinetiq" className="project chapter"><div className="section-label"><span>01 / SELECTED WORK</span><span>COMPUTER VISION</span></div><div className="project-heading"><h2>KinetiQ<span>.</span></h2><p>See the mechanics<br/>of your movement.</p></div><div className="project-body"><p className="lead">A swing, a shot, a throw. Turn a video into a phase-by-phase look at your form.</p><p>I built a motion-analysis application that uses pose estimation to isolate movement phases and score joint angles against expected ranges.</p><div className="metadata"><span>React Native / FastAPI / MediaPipe</span><span>Firebase / Auth0</span><span>Evidence: working demo + local testing</span></div><Demo name="KinetiQ" src={kinetiqVideo} poster={kinetiqPoster}/><ProcessPath calm={calm}/><div className="phase-explorer"><div className="eyebrow">Inside the analysis / Five movement phases</div><div className="phase-tabs" role="tablist" aria-label="Movement phases">{phases.map(([title],i)=><button key={title} id={`phase-${i}`} role="tab" aria-selected={phase===i} aria-controls="phase-panel" onClick={()=>setPhase(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:4))%5;setPhase(next);document.getElementById(`phase-${next}`)?.focus();}}} tabIndex={phase===i?0:-1}><span>0{i+1}</span>{title}</button>)}</div><div id="phase-panel" role="tabpanel" aria-labelledby={`phase-${phase}`}><p>{phases[phase][1]}</p><small>Explanation of the analysis stages. Watch the recording above for actual output.</small></div></div><Disclosure title="The engineering decision"><p>Processing every frame made pose estimation expensive. The backend could skip frames or stall under load. I reworked processing around sampled snapshots to distribute the work more evenly.</p><p>The tradeoff is temporal detail: sampling reduces processing work, but a brief movement can fall between samples. Choosing the sampling interval matters as much as making the pipeline faster.</p></Disclosure><Disclosure title="What I learned building KinetiQ"><p>Model integration is only part of the system. Token refresh, Auth0 callbacks, and persistent sessions each needed careful debugging. I learned to test the full path from authentication to completed analysis.</p></Disclosure></div></section>
 <section id="bite-right" className="project chapter"><div className="section-label"><span>02 / IN DEVELOPMENT</span><span>APPLIED AI</span></div><div className="project-heading"><h2>Bite Right<span>.</span></h2><p>More context.<br/>Before the first bite.</p></div><div className="project-body"><p className="lead">Built from a familiar question at the table: “What’s actually in this?”</p><p>Bite Right checks a food image or product label against dietary restrictions and presents potential matches. I built the current version around rule-based detection, with a trained model as the next step.</p><div className="metadata"><span>Image input / Restriction matching</span><span>Current stage: rule-based prototype</span></div><Demo name="Bite Right" src={biteVideo} poster={bitePoster}/><div className="result"><strong>95<span>%</span></strong><div><h3>Reported detection success</h3><p>From my local usage and test cases. This is a development result; a published evaluation set and broader validation are still needed.</p></div></div><Disclosure title="The problem behind Bite Right"><p>Friends and family repeatedly had to ask about ingredients in sauces and marinades, often without a clear answer. I wanted to make the available information easier to inspect against a person's restrictions.</p><p>The prototype flags possible matches. It cannot establish that a food is safe, and hidden ingredients or cross-contact are outside what an image can show.</p></Disclosure><Disclosure title="What comes next"><p>Train and evaluate a model across a wider range of foods and restrictions. Build a documented test set, inspect false negatives, and show uncertainty explicitly in the result.</p></Disclosure></div></section>
 <section id="archive" className="chapter archive"><div className="section-label"><span>03 / THE WORKBENCH</span><a href="https://github.com/Parth-2025">Full GitHub profile</a></div><h2>Other things<br/><em>I've put together.</em></h2><p className="archive-intro">Backend systems, developer tools, and products built around a problem I wanted to understand.</p><div className="archive-list">{[
 {n:'01',name:'Coach Connect',type:'MARKETPLACE / BACKEND',text:'Connecting UMD students with student-athletes for sport-specific coaching. I built the backend, MongoDB schema, and UMD SSO integration.',detail:'A unified profile model with a role field simplified booking queries that previously stitched together separate coach and student collections. Designed for the UMD community; the 40,000+ student figure describes the potential audience, not active users.',url:'https://github.com/Open-Sourcery-UMD/coachconnect'},
 {n:'02',name:'Github_PRReview',type:'DEVELOPER TOOLS / AI',text:'A code-change-risk agent that builds an import graph and examines how a pull request could affect the rest of a repository.',detail:'Static analysis flagged dynamic imports and framework entry points as dead code. I added an LLM verification step to help inspect those false positives. Built for a Palantir AIP submission.',url:'https://github.com/Parth-2025/Github_PRReview'},
 {n:'03',name:'ApplicationBot',type:'WORKFLOW / FULL STACK',text:'An internship application tracker with a React interface and Python backend. Postings move through new, tailored, applied, and outcome stages.',detail:'The project brings the application workflow into one place, making the current state of each opportunity explicit.',url:'https://github.com/Parth-2025/ApplicationBot'}
 ].map(p=><article className="archive-item" key={p.name}><span className="archive-number">{p.n}</span><div><span className="eyebrow">{p.type}</span><h3>{p.name}</h3><p>{p.text}</p><Disclosure title={`Inside ${p.name}`}><p>{p.detail}</p></Disclosure></div><a href={p.url} className="repo-link">Source code</a></article>)}</div></section>
 <section id="about" className="chapter about"><div className="section-label"><span>04 / BEHIND THE WORK</span><span>PARTH MOHAN</span></div><div className="about-heading"><h2>Curiosity,<br/><em>put to work.</em></h2><img src={profile} alt="Parth Mohan" width="220" height="260" loading="lazy"/></div><div className="about-content"><p className="lead">I'm studying computer science and machine learning at the University of Maryland.</p><p>I like the part of building where the first version meets an awkward edge case. That is where I learn the most about the model, the system around it, and the people using it.</p><div className="experience"><article><span className="eyebrow">MAY – AUG 2026</span><h3>Aptean</h3><p className="role">Software Engineering Intern</p><p>Built automated job orchestration for migrations and an MCP server connecting LLM agents to migration tooling.</p><p className="experience-result">300 hours to 30 hours <span>Manual migration time per customer. Project-reported result.</span></p></article><article><span className="eyebrow">SEP 2025 – PRESENT</span><h3>Computer Society</h3><p className="role">Project Manager</p><p>Leading architecture, milestones, and sprint planning for a team building an agentic AI system.</p></article><article><span className="eyebrow">JUN – JUL 2024</span><h3>Simcoach Games</h3><p className="role">Software Team Lead</p><p>Led an eight-person Unity team. Replaced whole-map germ-spread updates with active chunks to address stuttering in a kitchen simulation.</p></article></div></div></section>
 <footer id="contact"><div className="section-label"><span>05 / NEXT CONVERSATION</span><span>THANKS FOR LOOKING</span></div><h2>Let's build<br/><em>something useful.</em></h2><a className="email" href="mailto:parthmohan2006@gmail.com">parthmohan2006@gmail.com</a><div className="footer-bottom"><span>Parth Mohan / 2026</span><div><a href="https://github.com/Parth-2025">GitHub</a><a href="https://www.linkedin.com/in/parth-mohan/">LinkedIn</a><a href="#intro">Back to top</a></div></div><p className="credits">Motion studies with <a href="https://reactbits.dev/text-animations/particle-text">React Bits</a>, <a href="https://animejs.com">Anime.js</a>, <a href="https://skiper-ui.com/v1/skiper19">Skiper UI</a> and <a href="https://motion.dev">Motion</a>.</p></footer>
 </main></MotionConfig>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
